-- Create mechanical_inspections table
CREATE TABLE IF NOT EXISTS mechanical_inspections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(100) NULL,
    first_middle_name VARCHAR(150) NULL,
    business_name VARCHAR(255) NOT NULL,
    address_detail_1 VARCHAR(255) NULL,
    address_detail_2 VARCHAR(255) NULL,
    address_detail_3 VARCHAR(255) NULL,
    address_detail_4 VARCHAR(255) NULL,
    barangay VARCHAR(120) NULL,
    bus_id VARCHAR(50) NULL,
    renewal_status VARCHAR(50) NULL,
    annual_inspection_fee DECIMAL(12,2) DEFAULT 0,
    occupancy_permit_no VARCHAR(100) NULL,
    llc_no VARCHAR(100) NULL,
    line_grade_remarks TEXT NULL,
    civil_structural_remarks TEXT NULL,
    architectural_remarks TEXT NULL,
    architectural_fees DECIMAL(12,2) DEFAULT 0,
    sanitary_plumbing_remarks TEXT NULL,
    sanitary_plumbing_fees DECIMAL(12,2) DEFAULT 0,
    electrical_remarks TEXT NULL,
    electrical_fees DECIMAL(12,2) DEFAULT 0,
    electronics_remarks TEXT NULL,
    electronics_fees DECIMAL(12,2) DEFAULT 0,
    mechanical_remarks TEXT NULL,
    mechanical_fees DECIMAL(12,2) DEFAULT 0,
    total_fees DECIMAL(12,2) DEFAULT 0,
    inspection_date DATE NULL,
    contact_number VARCHAR(50) NULL,
    inspector VARCHAR(120) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

